import BackgroundPlate from "@/image-components/backgroundPlate/backgroundPlate";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>You talking to me?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <BackgroundPlate />
      </main>
    </>
  );
}
