import Head from "next/head";
import { Inter } from "@next/font/google";
import { FormEvent, useState } from "react";
import { lchown } from "fs";

const inter = Inter({ subsets: ["latin"] });

const apiCall = async (data: string) => {
  const res = await fetch("/api/chat", {
    method: "POST",
    headers: {
      Accept: "application/json, text/plain, */*",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });

  if (res.status === 200) {
    console.log("Response succeeded!");
    return res.json();
  } else {
    return "error No Response";
  }
};

export default function Home() {
  const [chat, setChat] = useState(["The Visitor: "]);

  const onSubmit = async (inputText: string) => {
    const callMsg = [...chat, inputText, "Robot: "].join("\n");
    const responsText = await apiCall(callMsg);

    setChat((chat) => [
      ...chat,
      inputText,
      "Robot: ",
      responsText.textOutput,
      "Visitor: ",
    ]);
  };

  return (
    <>
      <Head>
        <title>You talking to me?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="homepage__main">
        <div>
          <form onSubmit={(e: FormEvent) => {}}>
            <textarea
              onBlur={(e) => {
                console.log(e.currentTarget.value);
                onSubmit(e.currentTarget.value);
              }}
            ></textarea>
          </form>
          {chat.map((text: string, key: number) => {
            return <p key={key}>{text}</p>;
          })}
        </div>
      </main>
    </>
  );
}
